### ISSUE TITLE
reproduce hz / ignite benchmark results 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [gridgain/yardstick-hazelcast#3]
I have been unable to reproduce the results published hear.
https://ignite.apache.org/benchmarks/ignite-vs-hazelcast.html#serilizable-put-benchmark

I could not find a benchmark-ec2.properties   or   some 

```
# Run configuration which contains all benchmarks.
CONFIGS="\  ..... ... .. .
```

in this repo or  https://github.com/apacheignite/yardstick-ignite  which could be used to run the test
as configured on your comparison page.

I used the latest hat master of this repo and  hat master of https://github.com/apacheignite/yardstick-ignite,  but I was unable to reproduce the published results.

could you help me verify / reproduce the published results. thanks

**Comment by gAmUssA** [comment]
@dsetrakyan could you kindly point @Danny-Hazelcast?

**Comment by dsetrakyan** [comment]
Are you not able to run hazelcast or Ignite? For Ignite benchmarks, please use this repository: https://github.com/apacheignite/yardstick-ignite
